### ISSUE TITLE
Use of PETScConfig.cmake in other packages CMake

### ISSUE THREAD

**Issue by BarrySmith** [LBL-EESA/alquimia-dev#22]
Despite its name PETSc never intended other packages to use the PETScConfig.cmake (now named PETScBuildInternal.cmake to emphasis it is not for other uses).  

Thus we recommend moving away from using this file. @jedbrown has a findPETSc() cmake thing that is supposed to be used instead (I think) but I don't know enough about cmake to talk about.

**Comment by jnjohnsonlbl** [comment]
Happy to move away from this practice, as it's caused issues that you've pointed out. Let's chat at our meeting this week and see if we can figure something out.
