### ISSUE TITLE
proper include of PETSc

### ISSUE THREAD

**Issue by ecoon** [LBL-EESA/alquimia-dev#66]
@ghammond86 @smolins 

Question about the proper setup of Alquimia for use with PFloTran and PETSc.  I see that Alquimia expects that `$PETSC_DIR/$PETSC_ARCH/include/petsc` is in the list of include paths to search for include files (e.g. see:

https://github.com/LBL-EESA/alquimia-dev/blob/master/alquimia/pflotran_alquimia_interface.F90#L72

where `#include "finclude/petscsys.h"`, where `finclude` is installed by PETSc in the above location.

This requires that, at configure time, both `$PETSC_DIR/$PETSC_ARCH/include` and `$PETSC_DIR/$PETSC_ARCH/include/petsc` end up in the list of PETSC_INCLUDE_DIRS passed to CMake (or found via Find_PETSc).

Currently on OSX Catalina, my build of Alquimia (in Amanzi's bootstrap) isn't getting that.  I only get `$PETSC_DIR/$PETSC_ARCH/include` (though it is repeated twice).

This could be a bug in three places:

1. Fix Amanzi/SuperBuild to hand Alquimia PETSC_INCLUDE_DIRS that includes both.  I don't believe this to be right -- it should just hand Alquimia a PETSC_DIR in some form to assist Find_PETSc in looking in the right spot, and then Find_PETSc should set PETSC_INCLUDE_DIRS.
2. Fix Alquimia's Find_PETSc (does Alquimia provide one or it is using Cmake default version?  This would likely explain why I just started getting this bug, as I suspect Catalina has a very new cmake) to make sure that both paths are in the PETSC_INCLUDE_DIRS.
3. Fix Alquimia source to always prefix, e.g. `#include "petsc/finclude/petscsys.h`

I know Crunch does the third, and it looks like PFLOTRAN does the same (e.g.  https://bitbucket.org/pflotran/pflotran/src/17ee1985079c4377433fafad6bf5e7bb4f72ab28/src/pflotran/auxvars_flow.F90#lines-3. ).

So maybe the correct answer here is the third, and Alquimia should get updated to prefix its includes too?

**Comment by smolins** [comment]
Hi Ethan

I am forwarding this to Konstantin @lipnikov <https://github.com/lipnikov>
and David @jd-moulton <https://github.com/jd-moulton>. They are currently
upgrading these TPLs in Amanzi and they are dealing with this issue. If the
best solution could be on the Alquimia side, I would be happy to do 2 or 3.

David, Konstantin:

What is your take on this?

Thanks

Sergi

**Comment by smolins** [comment]
I think CMake 3.17 does have FindPETSc. David mentioned that the function we use differs from what could be found on the github dedicated project (last updated in 2018). Diffing Alquimia's and Amanzi's FindPETSc, I'm getting many differences.

This is from Amanzi's FindPETSc:


-- PETSC_VERSION      = 3.11

-- PETSC_INCLUDE_DIR  = /Users/lipnikov/ASCEM/TPLs-0.97.8-clang-10.0.1-ompi-4.0.3-dso/petsc-3.11.3/include

-- PETSC_INCLUDE_DIRS = /Users/lipnikov/ASCEM/TPLs-0.97.8-clang-10.0.1-ompi-4.0.3-dso/petsc-3.11.3/include;/Users/lipnikov/ASCEM/TPLs-0.97.8-clang-10.0.1-ompi-4.0.3-dso/include;/Users/lipnikov/ASCEM/build-tpls/install/openmpi-4.0.3-clang-10.0.1/include

________________________________
From: Sergi Molins Rafa <smolins@lbl.gov>
Sent: Thursday, August 13, 2020 10:07:29 AM
To: LBL-EESA/alquimia-dev
Cc: Lipnikov, Konstantin; Moulton, J. David
Subject: [EXTERNAL] Re: [LBL-EESA/alquimia-dev] proper include of PETSc (#66)

Hi Ethan

I am forwarding this to Konstantin @lipnikov<https://github.com/lipnikov> and David @jd-moulton<https://github.com/jd-moulton>. They are currently upgrading these TPLs in Amanzi and they are dealing with this issue. If the best solution could be on the Alquimia side, I would be happy to do 2 or 3.

David, Konstantin:

What is your take on this?

Thanks

Sergi

On Thu, Aug 13, 2020 at 7:47 AM Ethan Coon <notifications@github.com<mailto:notifications@github.com>> wrote:

@ghammond86<https://github.com/ghammond86> @smolins<https://github.com/smolins>

Question about the proper setup of Alquimia for use with PFloTran and PETSc. I see that Alquimia expects that $PETSC_DIR/$PETSC_ARCH/include/petsc is in the list of include paths to search for include files (e.g. see:

https://github.com/LBL-EESA/alquimia-dev/blob/master/alquimia/pflotran_alquimia_interface.F90#L72

where #include "finclude/petscsys.h", where finclude is installed by PETSc in the above location.

This requires that, at configure time, both $PETSC_DIR/$PETSC_ARCH/include and $PETSC_DIR/$PETSC_ARCH/include/petsc end up in the list of PETSC_INCLUDE_DIRS passed to CMake (or found via Find_PETSc).

Currently on OSX Catalina, my build of Alquimia (in Amanzi's bootstrap) isn't getting that. I only get $PETSC_DIR/$PETSC_ARCH/include (though it is repeated twice).

This could be a bug in three places:

  1.  Fix Amanzi/SuperBuild to hand Alquimia PETSC_INCLUDE_DIRS that includes both. I don't believe this to be right -- it should just hand Alquimia a PETSC_DIR in some form to assist Find_PETSc in looking in the right spot, and then Find_PETSc should set PETSC_INCLUDE_DIRS.
  2.  Fix Alquimia's Find_PETSc (does Alquimia provide one or it is using Cmake default version? This would likely explain why I just started getting this bug, as I suspect Catalina has a very new cmake) to make sure that both paths are in the PETSC_INCLUDE_DIRS.
  3.  Fix Alquimia source to always prefix, e.g. #include "petsc/finclude/petscsys.h

I know Crunch does the third, and it looks like PFLOTRAN does the same (e.g. https://bitbucket.org/pflotran/pflotran/src/17ee1985079c4377433fafad6bf5e7bb4f72ab28/src/pflotran/auxvars_flow.F90#lines-3. ).

So maybe the correct answer here is the third, and Alquimia should get updated to prefix its includes too?

**Comment by smolins** [comment]
typo :  think CMake 3.17 does NOT have FindPETSc.

________________________________

**Comment by ecoon** [comment]
> Hi Ethan I am forwarding this to Konstantin @lipnikov <https://github.com/lipnikov> and David @jd-moulton <https://github.com/jd-moulton>. They are currently upgrading these TPLs in Amanzi and they are dealing with this issue. If the best solution could be on the Alquimia side, I would be happy to do 2 or 3. David, Konstantin: What is your take on this? Thanks Sergi
> […](#)

Konstantin is the one who pointed out to me how Crunch did it (e.g. the third).  Seeing that both PFloTran and Crunch do it this way, it would make sense to me to do the same.

Should be as easy as:

`find . -name \*.F90 -print -o -name \*.h -print | xargs sed -i 's/include "finclude/include "petsc/finclude/g'`

**Comment by smolins** [comment]
Just implemented #3. Pull request took longer than hoped for because I had
to chase a bug in petsc's build system. If using CrunchFlow, please use
Satish's fix. If not, don't worry about it. The fix should make it to
v3.13.5, if all goes well.
Please let me know if this will work.

Sergi

**Comment by ecoon** [comment]
Is this ticket complete then Sergi?  I would like to close the corresponding one in Amanzi.

**Comment by smolins** [comment]
Yes. Closing.
